name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up linker
        run: apt update && apt install -y libssl-dev llvm lld && \
          update-alternatives --install /usr/bin/ld ld /usr/bin/ld.lld 20
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
