name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up linker
        run: docker build -t 860x9/rust_nuggets:latest .
      - name: Setup testing image
        run: docker run -p 80:80 kennethreitz/httpbin
      - name: Run tests in docker container
        run: docker run --rm 860x9/rust_nuggets cargo test --release --verbose
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        run: docker push 860x9/rust_nuggets:latest
