name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up linker
        run: docker build -t 860x9/rust_nuggets:latest .
      - name: Run tests in docker container
        run: docker run --rm rust_nuggets cargo test --release --verbose
